# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _JobMatcherLinux
else:
    import _JobMatcherLinux

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _JobMatcherLinux.delete_SwigPyIterator

    def value(self):
        return _JobMatcherLinux.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _JobMatcherLinux.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _JobMatcherLinux.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _JobMatcherLinux.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _JobMatcherLinux.SwigPyIterator_equal(self, x)

    def copy(self):
        return _JobMatcherLinux.SwigPyIterator_copy(self)

    def next(self):
        return _JobMatcherLinux.SwigPyIterator_next(self)

    def __next__(self):
        return _JobMatcherLinux.SwigPyIterator___next__(self)

    def previous(self):
        return _JobMatcherLinux.SwigPyIterator_previous(self)

    def advance(self, n):
        return _JobMatcherLinux.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _JobMatcherLinux.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _JobMatcherLinux.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _JobMatcherLinux.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _JobMatcherLinux.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _JobMatcherLinux.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _JobMatcherLinux.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _JobMatcherLinux:
_JobMatcherLinux.SwigPyIterator_swigregister(SwigPyIterator)

class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _JobMatcherLinux.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JobMatcherLinux.StringVector___nonzero__(self)

    def __bool__(self):
        return _JobMatcherLinux.StringVector___bool__(self)

    def __len__(self):
        return _JobMatcherLinux.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _JobMatcherLinux.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JobMatcherLinux.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JobMatcherLinux.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JobMatcherLinux.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JobMatcherLinux.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JobMatcherLinux.StringVector___setitem__(self, *args)

    def pop(self):
        return _JobMatcherLinux.StringVector_pop(self)

    def append(self, x):
        return _JobMatcherLinux.StringVector_append(self, x)

    def empty(self):
        return _JobMatcherLinux.StringVector_empty(self)

    def size(self):
        return _JobMatcherLinux.StringVector_size(self)

    def swap(self, v):
        return _JobMatcherLinux.StringVector_swap(self, v)

    def begin(self):
        return _JobMatcherLinux.StringVector_begin(self)

    def end(self):
        return _JobMatcherLinux.StringVector_end(self)

    def rbegin(self):
        return _JobMatcherLinux.StringVector_rbegin(self)

    def rend(self):
        return _JobMatcherLinux.StringVector_rend(self)

    def clear(self):
        return _JobMatcherLinux.StringVector_clear(self)

    def get_allocator(self):
        return _JobMatcherLinux.StringVector_get_allocator(self)

    def pop_back(self):
        return _JobMatcherLinux.StringVector_pop_back(self)

    def erase(self, *args):
        return _JobMatcherLinux.StringVector_erase(self, *args)

    def __init__(self, *args):
        _JobMatcherLinux.StringVector_swiginit(self, _JobMatcherLinux.new_StringVector(*args))

    def push_back(self, x):
        return _JobMatcherLinux.StringVector_push_back(self, x)

    def front(self):
        return _JobMatcherLinux.StringVector_front(self)

    def back(self):
        return _JobMatcherLinux.StringVector_back(self)

    def assign(self, n, x):
        return _JobMatcherLinux.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _JobMatcherLinux.StringVector_resize(self, *args)

    def insert(self, *args):
        return _JobMatcherLinux.StringVector_insert(self, *args)

    def reserve(self, n):
        return _JobMatcherLinux.StringVector_reserve(self, n)

    def capacity(self):
        return _JobMatcherLinux.StringVector_capacity(self)
    __swig_destroy__ = _JobMatcherLinux.delete_StringVector

# Register StringVector in _JobMatcherLinux:
_JobMatcherLinux.StringVector_swigregister(StringVector)

class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _JobMatcherLinux.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JobMatcherLinux.IntVector___nonzero__(self)

    def __bool__(self):
        return _JobMatcherLinux.IntVector___bool__(self)

    def __len__(self):
        return _JobMatcherLinux.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _JobMatcherLinux.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JobMatcherLinux.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JobMatcherLinux.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JobMatcherLinux.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JobMatcherLinux.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JobMatcherLinux.IntVector___setitem__(self, *args)

    def pop(self):
        return _JobMatcherLinux.IntVector_pop(self)

    def append(self, x):
        return _JobMatcherLinux.IntVector_append(self, x)

    def empty(self):
        return _JobMatcherLinux.IntVector_empty(self)

    def size(self):
        return _JobMatcherLinux.IntVector_size(self)

    def swap(self, v):
        return _JobMatcherLinux.IntVector_swap(self, v)

    def begin(self):
        return _JobMatcherLinux.IntVector_begin(self)

    def end(self):
        return _JobMatcherLinux.IntVector_end(self)

    def rbegin(self):
        return _JobMatcherLinux.IntVector_rbegin(self)

    def rend(self):
        return _JobMatcherLinux.IntVector_rend(self)

    def clear(self):
        return _JobMatcherLinux.IntVector_clear(self)

    def get_allocator(self):
        return _JobMatcherLinux.IntVector_get_allocator(self)

    def pop_back(self):
        return _JobMatcherLinux.IntVector_pop_back(self)

    def erase(self, *args):
        return _JobMatcherLinux.IntVector_erase(self, *args)

    def __init__(self, *args):
        _JobMatcherLinux.IntVector_swiginit(self, _JobMatcherLinux.new_IntVector(*args))

    def push_back(self, x):
        return _JobMatcherLinux.IntVector_push_back(self, x)

    def front(self):
        return _JobMatcherLinux.IntVector_front(self)

    def back(self):
        return _JobMatcherLinux.IntVector_back(self)

    def assign(self, n, x):
        return _JobMatcherLinux.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _JobMatcherLinux.IntVector_resize(self, *args)

    def insert(self, *args):
        return _JobMatcherLinux.IntVector_insert(self, *args)

    def reserve(self, n):
        return _JobMatcherLinux.IntVector_reserve(self, n)

    def capacity(self):
        return _JobMatcherLinux.IntVector_capacity(self)
    __swig_destroy__ = _JobMatcherLinux.delete_IntVector

# Register IntVector in _JobMatcherLinux:
_JobMatcherLinux.IntVector_swigregister(IntVector)

class IntVectorVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _JobMatcherLinux.IntVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JobMatcherLinux.IntVectorVector___nonzero__(self)

    def __bool__(self):
        return _JobMatcherLinux.IntVectorVector___bool__(self)

    def __len__(self):
        return _JobMatcherLinux.IntVectorVector___len__(self)

    def __getslice__(self, i, j):
        return _JobMatcherLinux.IntVectorVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JobMatcherLinux.IntVectorVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JobMatcherLinux.IntVectorVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JobMatcherLinux.IntVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JobMatcherLinux.IntVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JobMatcherLinux.IntVectorVector___setitem__(self, *args)

    def pop(self):
        return _JobMatcherLinux.IntVectorVector_pop(self)

    def append(self, x):
        return _JobMatcherLinux.IntVectorVector_append(self, x)

    def empty(self):
        return _JobMatcherLinux.IntVectorVector_empty(self)

    def size(self):
        return _JobMatcherLinux.IntVectorVector_size(self)

    def swap(self, v):
        return _JobMatcherLinux.IntVectorVector_swap(self, v)

    def begin(self):
        return _JobMatcherLinux.IntVectorVector_begin(self)

    def end(self):
        return _JobMatcherLinux.IntVectorVector_end(self)

    def rbegin(self):
        return _JobMatcherLinux.IntVectorVector_rbegin(self)

    def rend(self):
        return _JobMatcherLinux.IntVectorVector_rend(self)

    def clear(self):
        return _JobMatcherLinux.IntVectorVector_clear(self)

    def get_allocator(self):
        return _JobMatcherLinux.IntVectorVector_get_allocator(self)

    def pop_back(self):
        return _JobMatcherLinux.IntVectorVector_pop_back(self)

    def erase(self, *args):
        return _JobMatcherLinux.IntVectorVector_erase(self, *args)

    def __init__(self, *args):
        _JobMatcherLinux.IntVectorVector_swiginit(self, _JobMatcherLinux.new_IntVectorVector(*args))

    def push_back(self, x):
        return _JobMatcherLinux.IntVectorVector_push_back(self, x)

    def front(self):
        return _JobMatcherLinux.IntVectorVector_front(self)

    def back(self):
        return _JobMatcherLinux.IntVectorVector_back(self)

    def assign(self, n, x):
        return _JobMatcherLinux.IntVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _JobMatcherLinux.IntVectorVector_resize(self, *args)

    def insert(self, *args):
        return _JobMatcherLinux.IntVectorVector_insert(self, *args)

    def reserve(self, n):
        return _JobMatcherLinux.IntVectorVector_reserve(self, n)

    def capacity(self):
        return _JobMatcherLinux.IntVectorVector_capacity(self)
    __swig_destroy__ = _JobMatcherLinux.delete_IntVectorVector

# Register IntVectorVector in _JobMatcherLinux:
_JobMatcherLinux.IntVectorVector_swigregister(IntVectorVector)

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _JobMatcherLinux.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JobMatcherLinux.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _JobMatcherLinux.DoubleVector___bool__(self)

    def __len__(self):
        return _JobMatcherLinux.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _JobMatcherLinux.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JobMatcherLinux.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JobMatcherLinux.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JobMatcherLinux.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JobMatcherLinux.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JobMatcherLinux.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _JobMatcherLinux.DoubleVector_pop(self)

    def append(self, x):
        return _JobMatcherLinux.DoubleVector_append(self, x)

    def empty(self):
        return _JobMatcherLinux.DoubleVector_empty(self)

    def size(self):
        return _JobMatcherLinux.DoubleVector_size(self)

    def swap(self, v):
        return _JobMatcherLinux.DoubleVector_swap(self, v)

    def begin(self):
        return _JobMatcherLinux.DoubleVector_begin(self)

    def end(self):
        return _JobMatcherLinux.DoubleVector_end(self)

    def rbegin(self):
        return _JobMatcherLinux.DoubleVector_rbegin(self)

    def rend(self):
        return _JobMatcherLinux.DoubleVector_rend(self)

    def clear(self):
        return _JobMatcherLinux.DoubleVector_clear(self)

    def get_allocator(self):
        return _JobMatcherLinux.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _JobMatcherLinux.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _JobMatcherLinux.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _JobMatcherLinux.DoubleVector_swiginit(self, _JobMatcherLinux.new_DoubleVector(*args))

    def push_back(self, x):
        return _JobMatcherLinux.DoubleVector_push_back(self, x)

    def front(self):
        return _JobMatcherLinux.DoubleVector_front(self)

    def back(self):
        return _JobMatcherLinux.DoubleVector_back(self)

    def assign(self, n, x):
        return _JobMatcherLinux.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _JobMatcherLinux.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _JobMatcherLinux.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _JobMatcherLinux.DoubleVector_reserve(self, n)

    def capacity(self):
        return _JobMatcherLinux.DoubleVector_capacity(self)
    __swig_destroy__ = _JobMatcherLinux.delete_DoubleVector

# Register DoubleVector in _JobMatcherLinux:
_JobMatcherLinux.DoubleVector_swigregister(DoubleVector)

class State(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    samp_id = property(_JobMatcherLinux.State_samp_id_get, _JobMatcherLinux.State_samp_id_set)
    salary = property(_JobMatcherLinux.State_salary_get, _JobMatcherLinux.State_salary_set)
    similarity_base = property(_JobMatcherLinux.State_similarity_base_get, _JobMatcherLinux.State_similarity_base_set)
    salary_base = property(_JobMatcherLinux.State_salary_base_get, _JobMatcherLinux.State_salary_base_set)

    def __init__(self, sampid=0, salary=0, salary_base=0, similarity_base=0):
        _JobMatcherLinux.State_swiginit(self, _JobMatcherLinux.new_State(sampid, salary, salary_base, similarity_base))
    __swig_destroy__ = _JobMatcherLinux.delete_State

# Register State in _JobMatcherLinux:
_JobMatcherLinux.State_swigregister(State)

class JobMatcher(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, w, th, th2, w_a, w_b, n_top, skill_list, salary):
        _JobMatcherLinux.JobMatcher_swiginit(self, _JobMatcherLinux.new_JobMatcher(w, th, th2, w_a, w_b, n_top, skill_list, salary))

    def reset(self):
        return _JobMatcherLinux.JobMatcher_reset(self)

    def set_target(self, target):
        return _JobMatcherLinux.JobMatcher_set_target(self, target)

    def discount(self, n_cur, n_all):
        return _JobMatcherLinux.JobMatcher_discount(self, n_cur, n_all)

    def add(self, s):
        return _JobMatcherLinux.JobMatcher_add(self, s)

    def predict_salary(self, s):
        return _JobMatcherLinux.JobMatcher_predict_salary(self, s)

    def top_average_of_heap(self, Qs_tmp):
        return _JobMatcherLinux.JobMatcher_top_average_of_heap(self, Qs_tmp)

    def top_average(self):
        return _JobMatcherLinux.JobMatcher_top_average(self)
    __swig_destroy__ = _JobMatcherLinux.delete_JobMatcher

# Register JobMatcher in _JobMatcherLinux:
_JobMatcherLinux.JobMatcher_swigregister(JobMatcher)



